-- GERADO por scripts/generate-content.mjs
alter table public.contents add column if not exists slug text;
alter table public.contents add column if not exists lessons_count int default 0;
create unique index if not exists idx_contents_slug on public.contents(slug) where slug is not null;

truncate table public.contents restart identity cascade;

insert into public.contents
  (title, description, category, level, area, order_index, estimated_hours, slug, lessons_count)
values
('Fundamentos de Python', 'Este diretório organiza os fundamentos essenciais de Python em uma progressão de estudo. A ideia é começar pela sintaxe e pelos tipos, avançar para controle de fluxo, funções e escopo, depois chegar em recursos profissionais como tipagem, d', 'Fundamentos de Python', 'basico', 'Fundamentos', 1, 38, 'parte-1-basico', 15),
('Matemática para Programadores', 'Trilha completa e avançada de matemática para programação, ciência de dados, engenharia, finanças, simulação e computação científica com Python. O conteúdo parte de matemática básica e avança até cálculo multivariável, séries, equações dife', 'Matemática', 'intermediario', 'Matemática', 2, 30, 'parte-2-calculo-complete', 12),
('Estruturas de Dados e Algoritmos', 'Trilha completa e progressiva para dominar estruturas de dados, algoritmos e fundamentos práticos de Python. O conteúdo começa com primeiro programa, tipos, operadores e execução no terminal, avança por coleções, funções, iteradores, módulo', 'Estruturas de Dados', 'intermediario', 'Algoritmos', 3, 20, 'parte-2-estruturas', 8),
('Arquivos, Formatos e Serialização', 'Trilha completa e profissional para manipulação de arquivos em Python, cobrindo leitura/escrita, TXT, Markdown, CSV, JSON, XML, YAML, TOML, Pickle, Excel, Parquet, Avro, ORC, PDF, compressão, upload/download, streams, imagens e vídeos.', 'Arquivos', 'intermediario', 'Persistência', 4, 18, 'parte-3-arquivos', 7),
('Fundamentos de Banco de Dados', 'Trilha completa para dominar conceitos essenciais de bancos de dados relacionais: CRUD, joins, índices, transações, procedures, views, normalização e modelagem.', 'Banco de Dados', 'intermediario', 'Banco de Dados', 5, 20, 'parte-3-conceitos', 8),
('Programação Orientada a Objetos', 'Esta trilha consolida e expande os conteúdos de `poo_completo.md` e `poo_avancado.md`, adicionando os tópicos modernos de POO em Python: fundamentos, métodos mágicos, decorators, descriptors, protocols, metaclasses, SOLID, DDD, design patte', 'POO', 'intermediario', 'Engenharia de Software', 6, 35, 'parte-4-oop', 14),
('SOLID e Design de Software', 'Trilha completa e avançada para dominar SOLID em Python, do básico de orientação a objetos até arquitetura limpa, ports and adapters, injeção de dependência, testes e refatoração profissional.', 'SOLID & Design', 'avancado', 'Engenharia de Software', 7, 18, 'parte-4-solid', 7),
('Async, Concorrência e Mensageria', 'Trilha completa para dominar desenvolvimento assíncrono em Python, começando pelos fundamentos de concorrência e `async/await`, avançando para `asyncio`, `aiohttp`, `httpx`, drivers async de banco/cache, multithreading, multiprocessing, Cel', 'Async', 'avancado', 'Performance & Async', 8, 23, 'parte-5-async', 9),
('Algoritmos, Big O e Performance', 'Esta trilha organiza o conteúdo de Big O por categorias profissionais. O arquivo original `01_conceitos_completo.md` foi mantido como referência monolítica, mas o estudo principal deve seguir os diretórios abaixo.', 'Performance', 'avancado', 'Performance & Async', 9, 25, 'parte-5-bigo', 10),
('Automação, Scraping e Bots', 'Trilha completa e profissional para criar automações com Python: tarefas locais, scripts, CLI, web scraping, bots, Selenium, Playwright, BeautifulSoup, Scrapy, automação desktop, planilhas e agendamentos com `cron` e `schedule`.', 'Automação', 'intermediario', 'Automação', 10, 28, 'parte-6-automacao', 11),
('Excel e Planilhas com Python', 'Trilha completa e progressiva sobre Excel solo e Excel integrado com Python: fundamentos, fórmulas, funções, tabelas, validação, análise de dados, gráficos, dashboards, Power Query, automação, relatórios, pandas, openpyxl, XlsxWriter e proj', 'Excel', 'basico', 'Automação', 11, 20, 'parte-6-excel', 8),
('Finanças com Python', 'Trilha completa e progressiva sobre financas aplicadas com Python: fundamentos financeiros, matematica financeira, contabilidade, indicadores, renda fixa, renda variavel, derivativos, risco, carteira, backtesting, automacao de dados e proje', 'Finanças', 'intermediario', 'Finanças', 12, 23, 'parte-6-financas', 9),
('Finanças Quantitativas', 'Trilha completa e profissional de financas quantitativas com Python: dados de mercado, retornos, estatistica, series temporais, risco, otimizacao de carteiras, backtesting, modelos fatoriais, renda fixa quantitativa, derivativos, execucao, ', 'Finanças Quant', 'avancado', 'Finanças', 13, 30, 'parte-6-financas-quantitativas', 12),
('Redes, HTTP e Protocolos', 'Trilha completa e progressiva sobre redes e protocolos para Python: TCP/IP, sockets, HTTP/HTTPS, FTP, UDP e MQTT com IoT e Arduino.', 'Redes & HTTP', 'intermediario', 'Redes', 14, 15, 'parte-6-http', 6),
('Documentação de Software', 'Trilha completa e progressiva sobre documentação em projetos Python: Sphinx, MkDocs e Swagger/OpenAPI.', 'Documentação', 'intermediario', 'Qualidade', 15, 13, 'parte-6-python-doc', 5),
('Testes Automatizados', 'Trilha completa e progressiva para dominar testes em Python: Pytest, unit tests, integration tests, mocking, TDD, coverage e benchmark.', 'Testes', 'intermediario', 'Qualidade', 16, 18, 'parte-6-test', 7),
('Qualidade de Código', 'Trilha completa e avançada sobre ferramentas de qualidade de código em Python: Black, Ruff, Flake8, isort e MyPy.', 'Qualidade', 'intermediario', 'Qualidade', 17, 18, 'parte-6-code-quality', 7),
('APIs: REST, GraphQL, gRPC e WebSockets', 'Trilha completa e progressiva para construir APIs e backends profissionais com Python, cobrindo REST, GraphQL, WebSockets, gRPC e os frameworks Flask, FastAPI e Tornado.', 'APIs', 'avancado', 'Backend', 18, 25, 'parte-7-api', 10),
('ORMs e Bancos NoSQL', 'Trilha completa e profissional para trabalhar com ORMs relacionais e bancos NoSQL em Python. O foco é sair do uso básico até práticas avançadas de modelagem, consultas, performance, transações, migrações, integração com aplicações e operaçã', 'ORM & NoSQL', 'intermediario', 'Banco de Dados', 19, 20, 'parte-7-orm', 8),
('SQL e Bancos Relacionais', 'Esta trilha organiza o conteúdo de SQL por categorias profissionais. O arquivo original `01_sql.md` foi mantido como referência monolítica, mas o estudo principal deve seguir os diretórios abaixo.', 'SQL', 'intermediario', 'Banco de Dados', 20, 20, 'parte-7-sql', 8),
('Infraestrutura, CI/CD e Servidores', 'Trilha completa para dominar infraestrutura de aplicações Python: autenticação, middlewares, CORS, rate limiting, serialização, upload, background tasks, cache, logs, Linux, Nginx, Apache, Gunicorn, Uvicorn e CI/CD.', 'Infraestrutura', 'avancado', 'DevOps', 21, 25, 'parte-8-infra', 10),
('Internet das Coisas (IoT)', 'Trilha completa e progressiva sobre Internet das Coisas com Python: fundamentos, sensores, atuadores, microcontroladores, Raspberry Pi, MicroPython, MQTT, HTTP, gateways, APIs, bancos de dados, observabilidade, segurança, operação e projeto', 'IoT', 'avancado', 'IoT', 22, 20, 'parte-8-iot', 8),
('Observabilidade e Monitoramento', 'Trilha completa e progressiva sobre observabilidade para aplicações Python e sistemas backend: logging, monitoring, Prometheus, Grafana, OpenTelemetry e Sentry.', 'Observabilidade', 'avancado', 'DevOps', 23, 15, 'parte-8-observabilidade', 6),
('Deploy e Produção', 'Trilha completa e progressiva sobre colocar aplicações Python em produção: VPS, Docker Deploy, Kubernetes Deploy, Serverless, CI/CD pipelines, balanceamento de carga, escalabilidade e reverse proxy.', 'Produção', 'avancado', 'DevOps', 24, 20, 'parte-8-productions', 8),
('Data Science e Engenharia de Dados', 'Trilha completa e progressiva para dominar Ciência de Dados, Análise de Dados e Engenharia de Dados com Python. Esta organização expande e reorganiza o conteúdo de data_science.md, mantendo o arquivo original como guia geral e criando arqui', 'Data Science', 'intermediario', 'Data Science', 25, 28, 'parte-9-data-science', 11),
('Bioinformática com Python', 'Trilha completa e profunda sobre bioinformática usando Python. O objetivo é conectar biologia molecular, estatística, programação, análise de sequências, genômica, transcriptômica, variantes, filogenia, proteômica, bancos biológicos, pipeli', 'Bioinformática', 'avancado', 'Especializações', 26, 30, 'parte-10-bioinformatica', 12),
('Cibersegurança com Python', 'Trilha completa e progressiva sobre segurança para aplicações Python, APIs e backends: validação de entrada, secrets, criptografia, hashing, segurança em APIs, OAuth2, OpenID Connect, RBAC, ABAC, proteção contra SQL Injection, XSS, CSRF, au', 'Segurança', 'avancado', 'Segurança', 27, 23, 'parte-10-cyber-sec', 9),
('DevOps Avançado', 'Trilha completa e progressiva sobre containers e orquestração para aplicações Python, cobrindo Docker, Docker Compose e Kubernetes.', 'DevOps', 'avancado', 'DevOps', 28, 8, 'parte-10-devops', 3),
('Arquitetura de Software', 'Trilha completa e progressiva sobre arquitetura de software para aplicações Python e sistemas backend: MVC, MVVM, microsserviços, monolitos, DDD, arquitetura orientada a eventos e arquitetura hexagonal.', 'Arquitetura', 'avancado', 'Arquitetura', 29, 18, 'parte-10-engenharia', 7),
('Sistemas Embarcados', 'Trilha completa e profissional sobre sistemas embarcados usando Python, MicroPython, CircuitPython e Linux embarcado. O objetivo e conectar fundamentos de hardware, eletronica, firmware, comunicacao, sensores, atuadores, tempo real, IoT, se', 'Embarcados', 'avancado', 'IoT', 30, 28, 'parte-10-sistemas-embarcados', 11);
