import {
  dracula,
  githubDark,
  githubLight,
  vscodeDark,
  vscodeLight,
  monokai,
  monokaiDimmed,
  nord,
  tokyoNight,
  tokyoNightDay,
  tokyoNightStorm,
  solarizedDark,
  solarizedLight,
  okaidia,
  sublime,
  xcodeDark,
  xcodeLight,
  bbedit,
  androidstudio,
  atomone,
  aura,
  abcdef,
  material,
  materialDark,
  materialLight,
  gruvboxDark,
  gruvboxLight,
  duotoneDark,
  duotoneLight,
  noctisLilac,
  consoleDark,
  copilot,
} from "@uiw/codemirror-themes-all";
import type { Extension } from "@codemirror/state";

export const IDE_THEMES: { id: string; name: string; theme: Extension; dark: boolean }[] = [
  { id: "dracula", name: "Dracula", theme: dracula, dark: true },
  { id: "vscodeDark", name: "VS Code Dark", theme: vscodeDark, dark: true },
  { id: "githubDark", name: "GitHub Dark", theme: githubDark, dark: true },
  { id: "monokai", name: "Monokai", theme: monokai, dark: true },
  { id: "monokaiDimmed", name: "Monokai Dimmed", theme: monokaiDimmed, dark: true },
  { id: "tokyoNight", name: "Tokyo Night", theme: tokyoNight, dark: true },
  { id: "tokyoNightStorm", name: "Tokyo Night Storm", theme: tokyoNightStorm, dark: true },
  { id: "nord", name: "Nord", theme: nord, dark: true },
  { id: "solarizedDark", name: "Solarized Dark", theme: solarizedDark, dark: true },
  { id: "okaidia", name: "Okaidia", theme: okaidia, dark: true },
  { id: "sublime", name: "Sublime", theme: sublime, dark: true },
  { id: "xcodeDark", name: "Xcode Dark", theme: xcodeDark, dark: true },
  { id: "androidstudio", name: "Android Studio", theme: androidstudio, dark: true },
  { id: "atomone", name: "Atom One", theme: atomone, dark: true },
  { id: "aura", name: "Aura", theme: aura, dark: true },
  { id: "abcdef", name: "abcdef", theme: abcdef, dark: true },
  { id: "materialDark", name: "Material Dark", theme: materialDark, dark: true },
  { id: "material", name: "Material", theme: material, dark: true },
  { id: "gruvboxDark", name: "Gruvbox Dark", theme: gruvboxDark, dark: true },
  { id: "duotoneDark", name: "Duotone Dark", theme: duotoneDark, dark: true },
  { id: "consoleDark", name: "Console Dark", theme: consoleDark, dark: true },
  { id: "copilot", name: "Copilot", theme: copilot, dark: true },
  { id: "vscodeLight", name: "VS Code Light", theme: vscodeLight, dark: false },
  { id: "githubLight", name: "GitHub Light", theme: githubLight, dark: false },
  { id: "tokyoNightDay", name: "Tokyo Night Day", theme: tokyoNightDay, dark: false },
  { id: "solarizedLight", name: "Solarized Light", theme: solarizedLight, dark: false },
  { id: "xcodeLight", name: "Xcode Light", theme: xcodeLight, dark: false },
  { id: "bbedit", name: "BBEdit", theme: bbedit, dark: false },
  { id: "materialLight", name: "Material Light", theme: materialLight, dark: false },
  { id: "gruvboxLight", name: "Gruvbox Light", theme: gruvboxLight, dark: false },
  { id: "duotoneLight", name: "Duotone Light", theme: duotoneLight, dark: false },
  { id: "noctisLilac", name: "Noctis Lilac", theme: noctisLilac, dark: false },
];

export const DEFAULT_THEME = "dracula";
