import {
  LayoutDashboard,
  TrendingUp,
  Layers,
  GraduationCap,
  FileText,
  Library,
  Briefcase,
  Code2,
  FolderGit2,
  Settings,
  User,
  HelpCircle,
  MessagesSquare,
  FileSignature,
  Bot,
  Youtube,
  Award,
  SquareTerminal,
  Users,
  Route,
  Smartphone,
  Newspaper,
  Megaphone,
  LifeBuoy,
  Bell,
  ShieldCheck,
  Inbox,
  LineChart,
  Flag,
  MessageCircle,
  SlidersHorizontal,
  Receipt,
  Database,
  BadgeCheck,
  SearchCheck,
  Languages,
  Puzzle,
  Rocket,
  Flame,
  Map,
  CalendarRange,
  Swords,
  Bug,
  Compass,
  Mail,
  Globe,
  NotebookPen,
  Activity,
  Tag,
  ThumbsUp,
  type LucideIcon,
} from "lucide-react";

export type NavGroup = "Estudar" | "Recursos" | "Carreira" | "Conta" | "Admin";

export interface NavItem {
  title: string;
  href: string;
  icon: LucideIcon;
  group: NavGroup;
  adminOnly?: boolean;
  userOnly?: boolean;
  newTab?: boolean;
}

export const NAV_ITEMS: NavItem[] = [
  { title: "Início", href: "/inicio", icon: LayoutDashboard, group: "Estudar" },
  { title: "Trilhas", href: "/minhas-trilhas", icon: Route, group: "Estudar" },
  { title: "Comunidade", href: "/comunidade", icon: Users, group: "Estudar", newTab: true },
  { title: "Evolução", href: "/evolucao", icon: TrendingUp, group: "Estudar" },
  { title: "Stack", href: "/stack", icon: Layers, group: "Estudar" },
  {
    title: "Exercícios",
    href: "/exercicios",
    icon: Code2,
    group: "Estudar",
  },
  {
    title: "IDE Python",
    href: "/ide",
    icon: SquareTerminal,
    group: "Estudar",
    newTab: true,
  },
  {
    title: "Projetos",
    href: "/meus-projetos",
    icon: FolderGit2,
    group: "Estudar",
  },
  {
    title: "Construa seu SaaS",
    href: "/construir-saas",
    icon: Rocket,
    group: "Estudar",
  },
  { title: "Anotações", href: "/anotacoes", icon: NotebookPen, group: "Estudar" },
  { title: "Desafios Diários", href: "/desafios-diarios", icon: Flame, group: "Estudar" },
  { title: "Desafios", href: "/desafios", icon: Swords, group: "Estudar" },
  { title: "Debug — Bugs Reais", href: "/debug", icon: Bug, group: "Estudar" },
  { title: "Roadmaps", href: "/roadmaps", icon: Map, group: "Carreira" },
  { title: "Planejamento", href: "/planejamento", icon: CalendarRange, group: "Carreira" },
  { title: "Plano de Carreira", href: "/plano-carreira", icon: Compass, group: "Carreira" },
  {
    title: "Aulas Udemy",
    href: "/aulas-udemy",
    icon: GraduationCap,
    group: "Recursos",
  },
  {
    title: "Aulas YouTube",
    href: "/aulas-youtube",
    icon: Youtube,
    group: "Recursos",
  },
  { title: "Material", href: "/material", icon: FileText, group: "Recursos" },
  { title: "Livros", href: "/livros", icon: Library, group: "Recursos" },
  { title: "Aplicativo", href: "/aplicativo", icon: Smartphone, group: "Recursos" },
  { title: "Notícias Python", href: "/noticias-python", icon: Newspaper, group: "Recursos" },
  { title: "Novidades", href: "/novidades", icon: Megaphone, group: "Conta" },
  {
    title: "Carreira",
    href: "/minha-carreira",
    icon: Briefcase,
    group: "Carreira",
  },
  {
    title: "Especializações",
    href: "/especializacoes",
    icon: Award,
    group: "Carreira",
  },
  {
    title: "Consultor IA",
    href: "/consultor-ia",
    icon: Bot,
    group: "Carreira",
  },
  { title: "Vagas", href: "/vagas", icon: Briefcase, group: "Carreira" },
  {
    title: "Perguntas de Carreira",
    href: "/perguntas-carreira-python",
    icon: HelpCircle,
    group: "Carreira",
  },
  { title: "Entrevista com IA", href: "/entrevista-ia", icon: MessagesSquare, group: "Carreira" },
  { title: "Currículo", href: "/curriculo", icon: FileSignature, group: "Carreira" },
  { title: "Extensão VS Code", href: "/extensao", icon: Puzzle, group: "Carreira" },
  { title: "Perfil", href: "/perfil", icon: User, group: "Conta" },
  { title: "Notificações", href: "/notificacoes", icon: Bell, group: "Conta" },
  { title: "Suporte", href: "/suporte", icon: LifeBuoy, group: "Conta", userOnly: true },
  {
    title: "Configurações",
    href: "/configuracoes",
    icon: Settings,
    group: "Conta",
  },
];

export const NAV_GROUPS = ["Estudar", "Recursos", "Carreira", "Conta"] as const;

// ── Admin: hub + subrotas (menu colapsável, só para administradores) ──
export const ADMIN_NAV = {
  hub: { title: "Admin", href: "/admin", icon: ShieldCheck },
  items: [
    { title: "Configuração do site", href: "/admin/site", icon: SlidersHorizontal },
    { title: "Avisos & Notificações", href: "/admin/avisos", icon: Megaphone },
    { title: "Newsletter", href: "/admin/newsletter", icon: Mail },
    { title: "Visitantes", href: "/admin/visitantes", icon: Globe },
    { title: "Saúde da Plataforma", href: "/admin/saude", icon: Activity },
    { title: "Ofertas & Promoções", href: "/admin/ofertas", icon: Tag },
    { title: "Recomendações (NPS)", href: "/admin/recomendacoes", icon: ThumbsUp },
    { title: "Gerenciar IA", href: "/admin/ia", icon: Bot },
    { title: "SEO & Busca Google", href: "/admin/seo", icon: SearchCheck },
    { title: "Extensão VS Code", href: "/admin/extensao", icon: Puzzle },
    { title: "Tradução do site", href: "/admin/traducao", icon: Languages },
    { title: "Clientes & receita", href: "/admin/clientes", icon: LineChart },
    { title: "TrustMRR (verificado)", href: "/admin/trustmrr", icon: BadgeCheck },
    { title: "Taxas e custos", href: "/admin/taxas", icon: Receipt },
    { title: "Banco de dados", href: "/admin/banco", icon: Database },
    { title: "Moderação", href: "/admin/moderacao", icon: Flag },
    { title: "Mensagens", href: "/admin/mensagens", icon: Inbox },
    { title: "Chat ao vivo", href: "/admin/chat", icon: MessageCircle },
  ] as { title: string; href: string; icon: LucideIcon }[],
};
