import {
  Sprout,
  Code2,
  Server,
  BarChart3,
  Bot,
  Database,
  BrainCircuit,
  Brain,
  ServerCog,
  Boxes,
  Cpu,
  Shield,
  Blocks,
  Dna,
  CandlestickChart,
  Monitor,
  Crown,
  ScanEye,
  MessagesSquare,
  Gamepad2,
  Activity,
  Network,
  type LucideIcon,
} from "lucide-react";
import type { Tier } from "@/lib/billing-access";
import { FREE_MODULE_SLUG, TIER_RANK } from "@/lib/billing-access";

export interface Trilha {
  id: string;
  title: string;
  subtitle: string;
  goal: string; // "Quero ..."
  icon: LucideIcon;
  tier: Tier;
  areas: string[]; // ["*"] = todas
  moduleSlugs?: string[]; // mapeamento preciso (sobrepõe areas)
  level: "basico" | "intermediario" | "avancado";
  accent: string;
  topics: string[]; // currículo (chips)
  adModules: number; // escopo divulgado
  adLessons: number;
  adHours: number;
}

export const TRILHAS: Trilha[] = [
  // ───────────── GRÁTIS ─────────────
  {
    id: "primeiros-passos",
    title: "Primeiros Passos",
    subtitle: "Do zero ao seu primeiro programa",
    goal: "Estou começando agora em Python",
    icon: Sprout,
    tier: "free",
    areas: ["Fundamentos"],
    level: "basico",
    accent: "from-green/20 to-green/5 text-green",
    topics: [
      "Introdução ao Python 3.14+ e por que aprendê-lo",
      "Como o Python funciona (interpretador, bytecode)",
      "Instalação e ambiente (venv, pip, pyenv)",
      "VS Code + Cursor + Windsurf + Jupyter",
      "Sintaxe e indentação",
      "Variáveis, tipos e conversões",
      "Strings, f-strings e métodos de texto",
      "Números, operadores e math",
      "Booleanos e operadores lógicos",
      "Entrada e saída (input/print)",
      "Condicionais (if/elif/else, match)",
      "Loops (for/while, break/continue)",
      "Listas e métodos",
      "Tuplas, sets e quando usar cada um",
      "Dicionários e iteração",
      "List/dict/set comprehensions",
      "Funções, parâmetros e *args/**kwargs",
      "Escopo, closures e funções lambda",
      "Tratamento de erros (try/except/finally)",
      "Módulos, imports e a biblioteca padrão",
      "Leitura/escrita de arquivos (txt, CSV, JSON)",
      "Datas e horas (datetime)",
      "Expressões regulares (re) — introdução",
      "PEP8, type hints e boas práticas",
      "Depuração, logging e print debugging",
      "Testes básicos com assert e pytest",
      "Ambientes virtuais e gerenciamento de pacotes",
      "Git e GitHub do zero",
      "Panorama do ecossistema (web, dados, IA, automação)",
      "Mini-projetos guiados (CLI, jogo, automação)",
    ],
    adModules: 8,
    adLessons: 95,
    adHours: 45,
  },

  // ───────────── ESSENCIAL ─────────────
  {
    id: "python-developer",
    title: "Python Developer",
    subtitle: "Domínio completo da linguagem",
    goal: "Quero dominar Python de verdade",
    icon: Code2,
    tier: "essencial",
    areas: ["Algoritmos", "Engenharia de Software", "Qualidade", "Persistência", "Performance & Assincronia"],
    level: "intermediario",
    accent: "from-primary-light/20 to-primary/5 text-primary-light",
    topics: [
      "POO", "Dataclasses", "Type Hints", "Generics", "Protocols",
      "Design Patterns", "AsyncIO", "Context Managers", "Decorators avançados",
      "Metaclasses", "Testing com Pytest", "Packaging", "Publicação no PyPI",
    ],
    adModules: 15,
    adLessons: 120,
    adHours: 180,
  },
  {
    id: "backend",
    title: "Backend Developer",
    subtitle: "APIs modernas e sistemas escaláveis",
    goal: "Quero criar APIs e back-ends profissionais",
    icon: Server,
    tier: "essencial",
    areas: ["Backend", "Banco de Dados", "Redes"],
    level: "avancado",
    accent: "from-blue/20 to-blue/5 text-blue",
    topics: [
      "FastAPI", "Django", "Django Ninja", "SQLAlchemy", "Alembic",
      "PostgreSQL", "Redis", "JWT", "OAuth2", "WebSockets", "RabbitMQ",
      "Celery", "Microservices", "API Gateway", "Event Driven Architecture",
    ],
    adModules: 20,
    adLessons: 160,
    adHours: 250,
  },
  {
    id: "data-analytics",
    title: "Data Analytics",
    subtitle: "Dados para negócios",
    goal: "Quero analisar e visualizar dados",
    icon: BarChart3,
    tier: "essencial",
    areas: ["Data Science", "Matemática"],
    level: "intermediario",
    accent: "from-blue/20 to-blue/5 text-blue",
    topics: [
      "Pandas", "NumPy", "Polars", "Matplotlib", "Plotly", "Seaborn",
      "DuckDB", "Excel Automation", "Dashboarding", "BI com Python",
    ],
    adModules: 10,
    adLessons: 80,
    adHours: 120,
  },
  {
    id: "automacao",
    title: "Automação & Produtividade",
    subtitle: "Automatize qualquer processo",
    goal: "Quero automatizar tarefas e processos",
    icon: Bot,
    tier: "essencial",
    areas: ["Automação"],
    level: "intermediario",
    accent: "from-green/20 to-green/5 text-green",
    topics: [
      "Selenium", "Playwright", "PyAutoGUI", "OCR", "PDF Processing",
      "Scraping", "APIs", "Bots", "RPA", "Automação Empresarial",
    ],
    adModules: 12,
    adLessons: 90,
    adHours: 130,
  },
  {
    id: "desktop-apps",
    title: "Desktop Apps",
    subtitle: "Aplicações profissionais",
    goal: "Quero criar apps desktop e jogos",
    icon: Monitor,
    tier: "essencial",
    areas: ["Desktop", "Jogos"],
    level: "intermediario",
    accent: "from-magenta/20 to-magenta/5 text-magenta",
    topics: [
      "PySide6", "Qt Designer", "Flet", "Tkinter Moderno",
      "Tauri + Python", "Desktop Packaging",
    ],
    adModules: 8,
    adLessons: 60,
    adHours: 90,
  },

  // ───────────── COMPLETO ─────────────
  {
    id: "engenharia-dados",
    title: "Engenharia de Dados",
    subtitle: "Dados em escala",
    goal: "Quero construir pipelines de dados",
    icon: Database,
    tier: "completo",
    areas: ["Engenharia de Dados"],
    level: "avancado",
    accent: "from-magenta/20 to-magenta/5 text-magenta",
    topics: [
      "Apache Airflow", "Kafka", "Spark", "PySpark", "Delta Lake",
      "Data Warehouse", "ETL", "ELT", "Data Lake", "Lakehouse",
    ],
    adModules: 15,
    adLessons: 130,
    adHours: 200,
  },
  {
    id: "machine-learning",
    title: "Machine Learning & IA",
    subtitle: "IA moderna com Python",
    goal: "Quero trabalhar com IA e machine learning",
    icon: BrainCircuit,
    tier: "completo",
    areas: ["Machine Learning"],
    level: "avancado",
    accent: "from-green/20 to-green/5 text-green",
    topics: [
      "Scikit-Learn", "TensorFlow", "PyTorch", "HuggingFace", "LangChain",
      "LlamaIndex", "RAG", "Fine-Tuning", "Agentes IA", "Multi-Agent Systems",
    ],
    adModules: 18,
    adLessons: 150,
    adHours: 220,
  },
  {
    id: "devops-cloud",
    title: "DevOps & Cloud",
    subtitle: "Infraestrutura para Python",
    goal: "Quero deploy, infra e nuvem",
    icon: ServerCog,
    tier: "completo",
    areas: ["DevOps", "Performance & Assincronia"],
    level: "avancado",
    accent: "from-blue/20 to-blue/5 text-blue",
    topics: [
      "Docker", "Docker Compose", "Kubernetes", "Terraform", "GitHub Actions",
      "CI/CD", "AWS", "GCP", "Azure", "Observabilidade",
    ],
    adModules: 12,
    adLessons: 100,
    adHours: 150,
  },
  {
    id: "arquitetura",
    title: "Arquitetura de Software",
    subtitle: "Sistemas de alta escala",
    goal: "Quero projetar sistemas robustos",
    icon: Boxes,
    tier: "completo",
    areas: ["Arquitetura", "Engenharia de Software"],
    level: "avancado",
    accent: "from-primary-light/20 to-primary/5 text-primary-light",
    topics: [
      "Clean Architecture", "DDD", "Hexagonal Architecture", "CQRS",
      "Event Sourcing", "SOLID", "Design Patterns Avançados", "Arquiteturas Distribuídas",
    ],
    adModules: 10,
    adLessons: 90,
    adHours: 140,
  },
  {
    id: "iot",
    title: "IoT & Embarcados",
    subtitle: "Python no mundo físico",
    goal: "Quero programar dispositivos e IoT",
    icon: Cpu,
    tier: "completo",
    areas: ["IoT"],
    level: "avancado",
    accent: "from-green/20 to-green/5 text-green",
    topics: [
      "Raspberry Pi", "MicroPython", "ESP32", "Sensores", "MQTT", "Edge Computing",
    ],
    adModules: 8,
    adLessons: 60,
    adHours: 90,
  },
  {
    id: "cyber-security",
    title: "Cyber Security com Python",
    subtitle: "Segurança ofensiva e defensiva",
    goal: "Quero atuar com segurança",
    icon: Shield,
    tier: "completo",
    areas: ["Segurança"],
    level: "avancado",
    accent: "from-magenta/20 to-magenta/5 text-magenta",
    topics: [
      "Pentest Automation", "Network Analysis", "Packet Inspection",
      "Ethical Hacking", "Malware Analysis", "Security Tools",
    ],
    adModules: 10,
    adLessons: 85,
    adHours: 120,
  },
  {
    id: "blockchain",
    title: "Blockchain com Python",
    subtitle: "Web3 e contratos inteligentes",
    goal: "Quero trabalhar com Web3",
    icon: Blocks,
    tier: "completo",
    areas: [],
    moduleSlugs: ["ext-blockchain-e-web3"],
    level: "avancado",
    accent: "from-blue/20 to-blue/5 text-blue",
    topics: [
      "Web3.py", "Ethereum", "Solidity Integration", "Smart Contracts", "DeFi", "NFTs",
    ],
    adModules: 8,
    adLessons: 70,
    adHours: 100,
  },
  {
    id: "bioinformatica",
    title: "Bioinformática",
    subtitle: "Ciência aplicada",
    goal: "Quero usar Python na biologia",
    icon: Dna,
    tier: "completo",
    areas: [],
    moduleSlugs: ["parte-10-bioinformatica"],
    level: "avancado",
    accent: "from-green/20 to-green/5 text-green",
    topics: [
      "Biopython", "Genômica", "DNA Analysis", "Machine Learning para Biologia",
    ],
    adModules: 6,
    adLessons: 50,
    adHours: 80,
  },
  {
    id: "quant-financas",
    title: "Quant & Finanças",
    subtitle: "Mercado financeiro",
    goal: "Quero atuar no mercado financeiro",
    icon: CandlestickChart,
    tier: "completo",
    areas: [],
    moduleSlugs: ["parte-6-financas", "parte-6-financas-quantitativas"],
    level: "avancado",
    accent: "from-magenta/20 to-magenta/5 text-magenta",
    topics: [
      "Quantitative Finance", "Backtesting", "Trading Bots",
      "Risk Analysis", "Portfolio Optimization",
    ],
    adModules: 10,
    adLessons: 90,
    adHours: 130,
  },
  {
    id: "construir-llm",
    title: "Construir um LLM do zero",
    subtitle: "Crie seu próprio modelo de linguagem",
    goal: "Quero construir e treinar um LLM",
    icon: Brain,
    tier: "completo",
    areas: [],
    moduleSlugs: ["ext-construindo-um-llm-do-zero"],
    level: "avancado",
    accent: "from-magenta/20 to-primary/5 text-magenta",
    topics: [
      "Tokenização (BPE)",
      "Embeddings",
      "Self-attention",
      "Arquitetura Transformer",
      "Multi-head attention",
      "Positional encoding",
      "Treino com PyTorch",
      "Pré-treino e fine-tuning",
      "LoRA / QLoRA",
      "RLHF e alinhamento",
      "Quantização e inferência",
      "Servir o modelo (vLLM)",
    ],
    adModules: 12,
    adLessons: 110,
    adHours: 160,
  },

  // ───────────── NOVAS TRILHAS ─────────────
  {
    id: "visao-computacional",
    title: "Visão Computacional",
    subtitle: "Ensine máquinas a enxergar com Python",
    goal: "Quero trabalhar com imagens e vídeo + IA",
    icon: ScanEye,
    tier: "completo",
    areas: ["Machine Learning"],
    level: "avancado",
    accent: "from-cyan-400/20 to-primary/5 text-cyan-400",
    topics: [
      "Fundamentos de imagem digital (pixels, canais, espaços de cor)",
      "OpenCV: leitura, transformações e filtros",
      "Detecção de bordas (Canny), contornos e morfologia",
      "Histogramas, thresholding e segmentação clássica",
      "Feature matching (SIFT/ORB) e homografia",
      "Aumento de dados (data augmentation) para visão",
      "Redes convolucionais (CNN) do zero com PyTorch",
      "Transfer learning (ResNet, EfficientNet)",
      "Detecção de objetos (YOLO, Faster R-CNN)",
      "Segmentação semântica e de instâncias (U-Net, Mask R-CNN)",
      "Reconhecimento facial e landmarks",
      "OCR com Tesseract e modelos de deep learning",
      "Rastreamento de objetos em vídeo (tracking)",
      "Vision Transformers (ViT) e modelos multimodais (CLIP)",
      "Otimização e deploy na borda (ONNX, TensorRT)",
      "Projeto: pipeline de inspeção visual em tempo real",
    ],
    adModules: 14,
    adLessons: 130,
    adHours: 170,
  },
  {
    id: "nlp-llms",
    title: "NLP & LLMs Aplicados",
    subtitle: "Processamento de linguagem e IA generativa na prática",
    goal: "Quero criar produtos com LLMs e NLP",
    icon: MessagesSquare,
    tier: "completo",
    areas: ["Machine Learning"],
    level: "avancado",
    accent: "from-violet-400/20 to-primary/5 text-violet-400",
    topics: [
      "Pré-processamento de texto (tokenização, lematização, stopwords)",
      "Representações: TF-IDF, word2vec, embeddings contextuais",
      "Classificação de texto e análise de sentimento",
      "NER, POS tagging e extração de informação",
      "Transformers e a biblioteca Hugging Face",
      "Fine-tuning de modelos (BERT, RoBERTa)",
      "Engenharia de prompts e few-shot",
      "RAG: embeddings + bancos vetoriais (pgvector, FAISS, Chroma)",
      "Chunking, reranking e avaliação de RAG",
      "Function calling e ferramentas (tools)",
      "Agentes e orquestração (LangChain, LlamaIndex)",
      "Guardrails, avaliação e mitigação de alucinação",
      "Custos, latência, caching e streaming de tokens",
      "Fine-tuning eficiente (LoRA/QLoRA) e quantização",
      "Observabilidade de LLMs (traces, evals)",
      "Projeto: assistente RAG com seus próprios dados",
    ],
    adModules: 15,
    adLessons: 140,
    adHours: 180,
  },
  {
    id: "game-dev",
    title: "Game Dev com Python",
    subtitle: "Crie jogos 2D do conceito ao executável",
    goal: "Quero criar jogos com Python",
    icon: Gamepad2,
    tier: "essencial",
    areas: ["Jogos"],
    level: "intermediario",
    accent: "from-pink-400/20 to-primary/5 text-pink-400",
    topics: [
      "Game loop, FPS e delta time",
      "Pygame: janelas, superfícies e eventos",
      "Sprites, animação e folhas de sprite",
      "Detecção de colisão (AABB, círculos, máscaras)",
      "Física básica (gravidade, velocidade, atrito)",
      "Entrada do jogador (teclado, mouse, gamepad)",
      "Câmeras, tilemaps e cenários com rolagem",
      "Máquinas de estado e cenas (menu, jogo, game over)",
      "Áudio: efeitos e trilha sonora",
      "IA de inimigos (pathfinding A*, comportamentos)",
      "Sistema de partículas e efeitos visuais",
      "HUD, pontuação e salvamento de progresso",
      "Polimento, juice e game feel",
      "Empacotar com PyInstaller e distribuir",
      "Introdução ao Godot com Python (GDScript x Python)",
      "Projeto: um jogo 2D completo publicável",
    ],
    adModules: 12,
    adLessons: 105,
    adHours: 120,
  },
  {
    id: "sre-confiabilidade",
    title: "SRE & Confiabilidade",
    subtitle: "Mantenha sistemas no ar em escala",
    goal: "Quero garantir sistemas confiáveis em produção",
    icon: Activity,
    tier: "suprema",
    areas: ["DevOps"],
    level: "avancado",
    accent: "from-emerald-400/20 to-primary/5 text-emerald-400",
    topics: [
      "Princípios de SRE: SLI, SLO, SLA e error budget",
      "Observabilidade: logs, métricas e traces (os 3 pilares)",
      "Prometheus, Grafana e alerting (Alertmanager)",
      "Tracing distribuído com OpenTelemetry",
      "Health checks, readiness e liveness probes",
      "Estratégias de deploy (blue-green, canary, rolling)",
      "Circuit breakers, retries e timeouts (resiliência)",
      "Rate limiting, bulkheads e degradação graciosa",
      "Capacity planning e teste de carga (Locust, k6)",
      "Chaos engineering e testes de falha",
      "Incident response, on-call e postmortems sem culpa",
      "Runbooks, automação e toil reduction",
      "Backups, disaster recovery e RTO/RPO",
      "Segurança operacional e gestão de segredos",
      "Custos em cloud (FinOps) e otimização",
      "Projeto: plataforma observável com SLOs e alertas",
    ],
    adModules: 14,
    adLessons: 125,
    adHours: 160,
  },
  {
    id: "backend-distribuido",
    title: "Backend Distribuído & Microsserviços",
    subtitle: "Arquiteturas resilientes em larga escala",
    goal: "Quero construir sistemas distribuídos robustos",
    icon: Network,
    tier: "completo",
    areas: ["Backend", "Arquitetura"],
    level: "avancado",
    accent: "from-blue-400/20 to-primary/5 text-blue-400",
    topics: [
      "Monólito x microsserviços: quando usar cada um",
      "Comunicação síncrona (REST, gRPC) e assíncrona (eventos)",
      "Mensageria com Kafka e RabbitMQ",
      "Padrões: Saga, Outbox, CQRS e Event Sourcing",
      "Idempotência, deduplicação e exactly-once",
      "Consistência eventual e o teorema CAP",
      "API Gateway, service discovery e service mesh",
      "Resiliência: circuit breaker, retry, backoff",
      "Cache distribuído com Redis (estratégias e invalidação)",
      "Bancos: sharding, replicação e leitura/escrita",
      "Transações distribuídas e two-phase commit",
      "Observabilidade e tracing entre serviços",
      "Contratos, versionamento e compatibilidade de API",
      "Testes de integração e contract testing",
      "Deploy com Docker, Kubernetes e Helm",
      "Projeto: e-commerce distribuído orientado a eventos",
    ],
    adModules: 16,
    adLessons: 150,
    adHours: 200,
  },

  // ───────────── SUPREMA ─────────────
  {
    id: "suprema",
    title: "Python Mastery — Trilha Suprema",
    subtitle: "Todos os módulos + projeto final SaaS",
    goal: "Quero dominar o ecossistema inteiro",
    icon: Crown,
    tier: "suprema",
    areas: ["*"],
    level: "avancado",
    accent: "from-primary/25 to-magenta/10 text-primary-light",
    topics: [
      "Backend", "Data Analytics", "Engenharia de Dados", "Machine Learning",
      "IA Generativa", "DevOps", "Cloud", "Arquitetura", "Desktop", "IoT",
      "Segurança", "Blockchain", "Finanças Quant", "Bioinformática",
      "Projeto Final: SaaS com FastAPI, Postgres, Redis, Docker, K8s, CI/CD, RAG, Agentes IA e deploy AWS",
    ],
    adModules: 120,
    adLessons: 1000,
    adHours: 2000,
  },
];

export function getTrilha(id: string): Trilha | undefined {
  return TRILHAS.find((t) => t.id === id);
}

/** Áreas cujo conteúdo é exclusivo do plano Completo (ou superior). */
export const COMPLETO_AREAS = [
  "Machine Learning",
  "Engenharia de Dados",
  "IoT",
  "Arquitetura",
  "Especializações",
  "Segurança",
];

/** Tier necessário para acessar um módulo de conteúdo. */
export function moduleTier(area: string, slug: string): Tier {
  if (slug === FREE_MODULE_SLUG) return "free";
  if (COMPLETO_AREAS.includes(area)) return "completo";
  return "essencial";
}

export function canAccess(userTier: Tier, required: Tier): boolean {
  return TIER_RANK[userTier] >= TIER_RANK[required];
}

/** Um módulo pertence à trilha? (por slug explícito ou por área; "*" = todas) */
export function moduleInTrilha(trilha: Trilha, area: string, slug: string): boolean {
  if (trilha.moduleSlugs && trilha.moduleSlugs.length) {
    return trilha.moduleSlugs.includes(slug);
  }
  return trilha.areas.includes("*") || trilha.areas.includes(area);
}
