/**
 * Gera os 5 temas da PyTrack a partir de paletas compactas.
 * Cada paleta vira um tema VS Code completo (workbench + syntax tunado p/ Python).
 * Uso: node scripts/gen-themes.mjs
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const OUT = join(process.cwd(), "themes");
mkdirSync(OUT, { recursive: true });

// Paletas — marca PyTrack (roxo #8257E5, verde #04D361, gradiente neon)
const PALETTES = [
  {
    file: "pytrack-dark.json",
    name: "PyTrack Dark",
    type: "dark",
    bg: "#18181B", bgDeep: "#0F0F11", bgSoft: "#1E1E22", panel: "#111113",
    fg: "#E4E4E7", fgDim: "#A1A1AA", line: "#27272A", sel: "#8257E540",
    accent: "#8257E5", accent2: "#9956F6",
    kw: "#9956F6", str: "#29E0A9", fn: "#5F75F2", num: "#E254FF",
    cls: "#04D361", var: "#E4E4E7", const: "#E254FF", comment: "#6B6B73",
    op: "#A78BFA", deco: "#F59E0B", typ: "#29E0A9", param: "#C7B6F2",
  },
  {
    file: "pytrack-midnight.json",
    name: "PyTrack Midnight",
    type: "dark",
    bg: "#0A0A0C", bgDeep: "#060608", bgSoft: "#101015", panel: "#08080A",
    fg: "#D9DCE6", fgDim: "#8B8FA3", line: "#1A1B22", sel: "#5F75F240",
    accent: "#5F75F2", accent2: "#7C8CF8",
    kw: "#7C8CF8", str: "#5EEAD4", fn: "#8B9DFF", num: "#C792EA",
    cls: "#56D4DD", var: "#D9DCE6", const: "#C792EA", comment: "#5A5F73",
    op: "#9DA8FF", deco: "#F0A35E", typ: "#5EEAD4", param: "#B8C0E8",
  },
  {
    file: "pytrack-neon.json",
    name: "PyTrack Neon",
    type: "dark",
    bg: "#121016", bgDeep: "#0C0A10", bgSoft: "#19161F", panel: "#0E0C12",
    fg: "#ECE6F5", fgDim: "#A89CB8", line: "#241F2D", sel: "#E254FF38",
    accent: "#E254FF", accent2: "#9956F6",
    kw: "#E254FF", str: "#29E0A9", fn: "#5F9CFF", num: "#FF8A3D",
    cls: "#5EEAD4", var: "#ECE6F5", const: "#FF8A3D", comment: "#6E6280",
    op: "#F472D0", deco: "#FFC857", typ: "#5EEAD4", param: "#D8B8F2",
  },
  {
    file: "pytrack-forest.json",
    name: "PyTrack Forest",
    type: "dark",
    bg: "#0E1512", bgDeep: "#09110D", bgSoft: "#13201B", panel: "#0A120F",
    fg: "#DCEAE2", fgDim: "#8FA89B", line: "#1C2A23", sel: "#04D36138",
    accent: "#04D361", accent2: "#29E0A9",
    kw: "#34D399", str: "#7DD3FC", fn: "#22D3A8", num: "#FBBF77",
    cls: "#5EEAD4", var: "#DCEAE2", const: "#FBBF77", comment: "#5E7368",
    op: "#6EE7B7", deco: "#FCD34D", typ: "#5EEAD4", param: "#A7D8C5",
  },
  {
    file: "pytrack-light.json",
    name: "PyTrack Light",
    type: "light",
    bg: "#FFFFFF", bgDeep: "#F4F4F5", bgSoft: "#FAFAFA", panel: "#F4F4F5",
    fg: "#18181B", fgDim: "#52525B", line: "#E4E4E7", sel: "#8257E526",
    accent: "#7C3AED", accent2: "#8257E5",
    kw: "#7C3AED", str: "#059669", fn: "#2563EB", num: "#C026D3",
    cls: "#0891B2", var: "#18181B", const: "#C026D3", comment: "#94A3B8",
    op: "#7C3AED", deco: "#D97706", typ: "#0891B2", param: "#5B21B6",
  },
];

const tc = (scope, foreground, fontStyle) => ({
  scope,
  settings: fontStyle ? { foreground, fontStyle } : { foreground },
});

function buildTheme(p) {
  return {
    $schema: "vscode://schemas/color-theme",
    name: p.name,
    type: p.type,
    semanticHighlighting: true,
    colors: {
      "editor.background": p.bg,
      "editor.foreground": p.fg,
      "editorLineNumber.foreground": p.fgDim + "66",
      "editorLineNumber.activeForeground": p.accent,
      "editorCursor.foreground": p.accent,
      "editor.selectionBackground": p.sel,
      "editor.selectionHighlightBackground": p.sel,
      "editor.lineHighlightBackground": p.bgSoft,
      "editor.wordHighlightBackground": p.accent + "22",
      "editor.findMatchBackground": p.accent + "55",
      "editor.findMatchHighlightBackground": p.accent + "2A",
      "editorBracketMatch.background": p.accent + "33",
      "editorBracketMatch.border": p.accent + "00",
      "editorIndentGuide.background1": p.line,
      "editorIndentGuide.activeBackground1": p.accent + "66",
      "editorWhitespace.foreground": p.line,
      "editorGutter.background": p.bg,
      "editorError.foreground": "#EF4444",
      "editorWarning.foreground": "#F59E0B",
      "editorInfo.foreground": p.fn,
      "editorHint.foreground": p.accent,
      // bracket pair colorization (gradiente da marca)
      "editorBracketHighlight.foreground1": p.accent2,
      "editorBracketHighlight.foreground2": p.str,
      "editorBracketHighlight.foreground3": p.fn,
      "editorBracketHighlight.foreground4": p.num,
      "editorBracketHighlight.foreground5": p.deco,
      "editorBracketHighlight.foreground6": p.cls,
      "editorBracketHighlight.unexpectedBracket.foreground": "#EF4444",
      // workbench
      "foreground": p.fg,
      "focusBorder": p.accent + "88",
      "selection.background": p.sel,
      "activityBar.background": p.bgDeep,
      "activityBar.foreground": p.fg,
      "activityBar.inactiveForeground": p.fgDim + "99",
      "activityBar.activeBorder": p.accent,
      "activityBarBadge.background": p.accent,
      "activityBarBadge.foreground": "#FFFFFF",
      "sideBar.background": p.bgDeep,
      "sideBar.foreground": p.fgDim,
      "sideBarTitle.foreground": p.fg,
      "sideBarSectionHeader.background": p.bgDeep,
      "sideBarSectionHeader.foreground": p.fg,
      "list.activeSelectionBackground": p.accent + "26",
      "list.activeSelectionForeground": p.fg,
      "list.hoverBackground": p.bgSoft,
      "list.inactiveSelectionBackground": p.bgSoft,
      "list.highlightForeground": p.accent2,
      "tree.indentGuidesStroke": p.line,
      "statusBar.background": p.bgDeep,
      "statusBar.foreground": p.fgDim,
      "statusBar.noFolderBackground": p.bgDeep,
      "statusBar.debuggingBackground": p.accent,
      "statusBar.debuggingForeground": "#FFFFFF",
      "statusBarItem.remoteBackground": p.accent,
      "statusBarItem.remoteForeground": "#FFFFFF",
      "titleBar.activeBackground": p.bgDeep,
      "titleBar.activeForeground": p.fg,
      "titleBar.inactiveBackground": p.bgDeep,
      "titleBar.inactiveForeground": p.fgDim,
      "tab.activeBackground": p.bg,
      "tab.activeForeground": p.fg,
      "tab.inactiveBackground": p.bgDeep,
      "tab.inactiveForeground": p.fgDim,
      "tab.activeBorderTop": p.accent,
      "tab.activeBorder": p.accent + "00",
      "tab.border": p.bgDeep,
      "editorGroupHeader.tabsBackground": p.bgDeep,
      "panel.background": p.panel,
      "panel.border": p.line,
      "panelTitle.activeForeground": p.fg,
      "panelTitle.activeBorder": p.accent,
      "terminal.background": p.panel,
      "terminal.foreground": p.fg,
      "terminalCursor.foreground": p.accent,
      "terminal.ansiBlue": p.fn,
      "terminal.ansiBrightBlue": p.fn,
      "terminal.ansiGreen": p.str,
      "terminal.ansiBrightGreen": p.str,
      "terminal.ansiMagenta": p.num,
      "terminal.ansiBrightMagenta": p.num,
      "terminal.ansiCyan": p.typ,
      "terminal.ansiYellow": p.deco,
      "terminal.ansiRed": "#EF4444",
      "input.background": p.bgSoft,
      "input.foreground": p.fg,
      "input.border": p.line,
      "inputOption.activeBorder": p.accent,
      "dropdown.background": p.bgSoft,
      "dropdown.foreground": p.fg,
      "button.background": p.accent,
      "button.foreground": "#FFFFFF",
      "button.hoverBackground": p.accent2,
      "badge.background": p.accent,
      "badge.foreground": "#FFFFFF",
      "progressBar.background": p.accent,
      "scrollbarSlider.background": p.fgDim + "22",
      "scrollbarSlider.hoverBackground": p.fgDim + "44",
      "scrollbarSlider.activeBackground": p.accent + "66",
      "editorWidget.background": p.bgDeep,
      "editorWidget.border": p.line,
      "editorSuggestWidget.background": p.bgDeep,
      "editorSuggestWidget.selectedBackground": p.accent + "26",
      "editorSuggestWidget.highlightForeground": p.accent2,
      "editorHoverWidget.background": p.bgDeep,
      "editorHoverWidget.border": p.line,
      "peekViewEditor.background": p.bgSoft,
      "notifications.background": p.bgDeep,
      "notificationCenterHeader.background": p.bgDeep,
      "gitDecoration.modifiedResourceForeground": p.deco,
      "gitDecoration.addedResourceForeground": p.str,
      "gitDecoration.deletedResourceForeground": "#EF4444",
      "gitDecoration.untrackedResourceForeground": p.cls,
      "minimap.selectionHighlight": p.accent,
      "textLink.foreground": p.accent2,
      "textLink.activeForeground": p.accent,
    },
    tokenColors: [
      tc(["comment", "punctuation.definition.comment"], p.comment, "italic"),
      tc("string", p.str),
      tc(["string.quoted.docstring", "string.quoted.multi.python"], p.comment, "italic"),
      tc(["constant.numeric", "constant.numeric.python"], p.num),
      tc(["constant.language", "constant.language.python"], p.const),
      tc(["constant.character", "constant.other"], p.const),
      tc(["keyword", "keyword.control", "keyword.control.flow.python", "keyword.control.import.python"], p.kw, "bold"),
      tc(["keyword.operator", "keyword.operator.logical.python", "keyword.operator.python"], p.op),
      tc(["storage", "storage.type", "storage.type.function.python", "storage.type.class.python", "storage.modifier"], p.kw, "italic"),
      tc(["entity.name.function", "meta.function-call.python", "support.function", "support.function.builtin.python"], p.fn),
      tc(["entity.name.class", "entity.name.type", "entity.name.type.class.python", "support.type", "support.class"], p.cls, "bold"),
      tc(["support.type.python", "meta.function.parameters.python support.type"], p.typ),
      tc(["variable", "variable.other", "meta.variable.python"], p.var),
      tc(["variable.parameter", "variable.parameter.function-call.python"], p.param, "italic"),
      tc(["variable.language.special.self.python", "variable.language.special.cls.python", "variable.language"], p.deco, "italic"),
      tc(["meta.decorator", "entity.name.function.decorator.python", "punctuation.definition.decorator.python"], p.deco),
      tc(["meta.import", "keyword.control.import"], p.kw),
      tc(["entity.name.namespace", "support.module"], p.cls),
      tc(["punctuation", "punctuation.separator", "punctuation.definition"], p.fgDim),
      tc(["meta.string.regexp", "string.regexp"], p.deco),
      // f-strings: marca de interpolação realçada
      tc(["meta.fstring.python", "string.interpolated.python"], p.str),
      tc(["constant.character.format.placeholder", "meta.interpolation.python"], p.accent2, "bold"),
      // tipos de retorno / type hints
      tc(["meta.typehint.python", "meta.function.return-type.python"], p.typ, "italic"),
      // markdown/json úteis
      tc(["markup.heading", "entity.name.section"], p.accent2, "bold"),
      tc(["markup.bold"], p.fg, "bold"),
      tc(["markup.italic"], p.fg, "italic"),
      tc(["markup.inline.raw", "markup.fenced_code"], p.str),
      tc(["support.type.property-name.json"], p.fn),
      tc(["invalid", "invalid.illegal"], "#EF4444"),
    ],
  };
}

let count = 0;
for (const p of PALETTES) {
  writeFileSync(join(OUT, p.file), JSON.stringify(buildTheme(p), null, 2) + "\n");
  count++;
}
console.log(`Temas gerados: ${count} → themes/`);
PALETTES.forEach((p) => console.log(` - ${p.name} (${p.typ})`));
